# Generated by Django 6.0.5 on 2026-05-26 17:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
