# Generated by Django 6.0.5 on 2026-05-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_project_cover_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="project",
            name="cover_image",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
